version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - bd-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
volumes:
  bd-data:
